### ISSUE TITLE
Hi, i met this problem. How do you get inception_model.pyc?

### ISSUE THREAD

**Issue by machineNo6** [TrustAI/DeepSAVA#1]
Traceback (most recent call last):
  File "/home/chentong/DeepSAVA/DeepSAVA-main/test_gen.py", line 6, in <module>
    import models
  File "/home/chentong/DeepSAVA/DeepSAVA-main/models/__init__.py", line 10, in <module>
    from inception.inception import inception_model
ImportError: bad magic number in 'inception.inception.inception_model': b'\x03\xf3\r\n'

**Comment by stark-akib** [comment]
Hello @machineNo6 , were you able to fix this error? I am also stuck at this "bad magic number" error.

I am using Python 3.7, with Tensorflow 1.15. After numerous searches, I found out that the "bad magic number" error occurs when there is a mismatch between the python versions of the compiled .pyc file and the environment python version. 

@WenjieRuan Can you please direct us on how to solve this? 
Thank you.

**Comment by machineNo6** [comment]
@stark-akib DeepSAVA-main/models/__init__.py ‘from inception.inception import inception_model’ and ‘from vgg import VGG16’

If you comment them out, you can run the i3d in the github instructions, but I didn’t try other models, sorry

It has been a long time since i repro it so I can't remember clearly.
